@ECHO OFF
REM - Arguments from user input
REM - SET APP_PATH=%1
REM - SET LICENSE=%2
SET ROUTER_COUNT=%1
SET WIRED_NODE_COUNT=%2
SET GNB_COUNT=%3
SET UE_COUNT=%4
SET EPC_COUNT=%5
SET APP_COUNT=%6
SET APP_PATH=%7
SET EXP_NAME=%8
SET VER_NAME=%9
SET VER_NUM=%10
SET SIM_TIME=%11


NetSim_Scenario_Generation_5GLTE.exe %ROUTER_COUNT% %WIRED_NODE_COUNT% %GNB_COUNT% %UE_COUNT% %EPC_COUNT% %APP_COUNT% %APP_PATH% %EXP_NAME% %VER_NAME% %VER_NUM% %SIM_TIME%

START "" /w /MIN %APP_PATH%\5G_Core.exe %APP_PATH% %APP_PATH% %APP_PATH%
						
			